### ISSUE TITLE
[Feature Request] Store config file in .vscode directory

### ISSUE THREAD

**Issue by lonix1** [george3447/docker-run#28]
The config file must be in the workspace root: `project/.dockerrc`. However config files are typically kept in the config directory: `project/.vscode/.dockerrc`.

Please allow us to keep it in the config directory instead?

**Comment by george3447** [comment]
Thanks for the feature request, I have intentionally made this a requirement because container ids will be different for each workspace and people tend to commit the .vscode folder to git.

**Comment by lonix1** [comment]
Ah okay now I understand! :) If feature #29 is implemented, then this one would make sense. Not otherwise.

Actually, it was fully my intention to commit the file to source control. But yes it only makes sense if one can specify the "docker-compose.yml" rather than use IDs. I'll update the other issue instead.
